DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS reservation;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE reservation (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    room_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    book_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    time_begin TIME NOT NULL DEFAULT CURRENT_TIME, 
    time_end TIME NOT NULL DEFAULT CURRENT_TIME, 
    booked_date DATE NOT NULL DEFAULT CURRENT_DATE
);